/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Brian Okungu
 */
public class Addmasks extends javax.swing.JFrame {

    /**
     * Creates new form Addmasks
     */
    public Addmasks() {
        initComponents();
        stucheck.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        uni1 = new javax.swing.JTextField();
        uni2 = new javax.swing.JTextField();
        uni3 = new javax.swing.JTextField();
        uni4 = new javax.swing.JTextField();
        uni5 = new javax.swing.JTextField();
        uni6 = new javax.swing.JTextField();
        uni7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stname = new javax.swing.JTextField();
        reg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        stucheck = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "unit1", "unit2", "unit3", "unit4", "unit5", "unit6", "unit7"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 131, 887, 151));
        getContentPane().add(uni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 356, 595, 27));
        getContentPane().add(uni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 389, 595, 27));
        getContentPane().add(uni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 421, 595, 27));

        uni4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uni4ActionPerformed(evt);
            }
        });
        getContentPane().add(uni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 466, 595, 27));
        getContentPane().add(uni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 504, 595, 27));
        getContentPane().add(uni6, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 542, 595, 27));
        getContentPane().add(uni7, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 587, 595, 29));

        jLabel1.setText("Add units to grade");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 157, 23));

        jCheckBox1.setText("Session1.1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));

        jCheckBox2.setText("Session1.2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jCheckBox3.setText("Session2.1");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        jCheckBox4.setText("Session2.2");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        jCheckBox5.setText("Session3.1");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, -1));

        jCheckBox6.setText("Session3.2");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, -1, -1));

        jCheckBox7.setText("Session4.1");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, -1, -1));

        jCheckBox8.setText("Session4.2");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Student Regno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        stname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnameActionPerformed(evt);
            }
        });
        getContentPane().add(stname, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 11, 202, 29));
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 51, 202, 28));

        jButton1.setText("Check if Student reported and register for units");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 90, -1, -1));

        stucheck.setText("Student never Reported or Registered Units");
        getContentPane().add(stucheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 18, -1, -1));

        jLabel4.setText("Unit Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 324, -1, -1));

        jLabel5.setText("Grade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 324, -1, -1));

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 614, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uni4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uni4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uni4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
                  try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from sessiontwoone";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
           
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void stnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try{
                String username1=stname.getText();
                String password1=reg.getText();
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select * from brian where Firstname=? and RegNO=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, username1);
                pst.setString(2, password1);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    JOptionPane.showMessageDialog(null,"Student Reported and Registered for Units");

                }else{
                    
                    stucheck.setVisible(true);
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
                  try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from sessiontwotwo";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
                  try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from sessionthreeone";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
                  try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from sessionthreetwo";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        uni1.setText(model.getValueAt(row, 1).toString());
        uni2.setText(model.getValueAt(row, 2).toString());
        uni3.setText(model.getValueAt(row, 3).toString());
        uni4.setText(model.getValueAt(row, 4).toString());
        uni5.setText(model.getValueAt(row, 5).toString());
        uni6.setText(model.getValueAt(row, 6).toString());
        uni7.setText(model.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox3.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into examinationtwoone(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
        }
        else if (jCheckBox4.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into examinationtwotwo(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
        }
       else if (jCheckBox5.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into examinationthreeone(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
       }
            else if (jCheckBox6.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into examinationthreeone(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addmasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addmasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addmasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addmasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addmasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField stname;
    private javax.swing.JLabel stucheck;
    private javax.swing.JTable table;
    private javax.swing.JTextField uni1;
    private javax.swing.JTextField uni2;
    private javax.swing.JTextField uni3;
    private javax.swing.JTextField uni4;
    private javax.swing.JTextField uni5;
    private javax.swing.JTextField uni6;
    private javax.swing.JTextField uni7;
    // End of variables declaration//GEN-END:variables
}
