/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Brian Okungu
 */
public class AdvisorConsole extends javax.swing.JFrame {

    /**
     * Creates new form AdvisorConsole
     */
    public String me;
    public String cou;
    public AdvisorConsole() {
        initComponents();
    }
       public AdvisorConsole(String username1,String number1){
        initComponents();
        
       
       
        
       
        sch.setText(username1);
        me = sch.getText();
        
        
         try{
               
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select course from adv where advisorname=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, me);
               
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    cou=rs.getString("course");
                    
                    
                    
                    //JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                    

                }else{
                    JOptionPane.showMessageDialog(null,"Wrong password or username");
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        uni1 = new javax.swing.JTextField();
        uni2 = new javax.swing.JTextField();
        uni3 = new javax.swing.JTextField();
        uni4 = new javax.swing.JTextField();
        uni5 = new javax.swing.JTextField();
        uni6 = new javax.swing.JTextField();
        uni7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        sch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COD UNIT CONFIRMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 107, 894, 67));

        jButton5.setText("CONFIRM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 518, -1, -1));

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Session1.1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 87, -1, -1));

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Session1.2");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 110, -1, -1));

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setText("Session2.1");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 133, -1, -1));

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setText("Session2.2");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 156, -1, -1));

        buttonGroup1.add(jCheckBox5);
        jCheckBox5.setText("Session3.1");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 182, -1, 20));

        buttonGroup1.add(jCheckBox6);
        jCheckBox6.setText("Session3.2");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 202, -1, -1));

        buttonGroup1.add(jCheckBox7);
        jCheckBox7.setText("Session4.1");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 228, -1, -1));

        buttonGroup1.add(jCheckBox8);
        jCheckBox8.setText("Session4.2");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 251, -1, -1));
        getContentPane().add(uni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 207, 579, 35));
        getContentPane().add(uni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 252, 579, 27));
        getContentPane().add(uni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 290, 579, 31));
        getContentPane().add(uni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 327, 579, 28));
        getContentPane().add(uni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 361, 579, 33));

        uni6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uni6ActionPerformed(evt);
            }
        });
        getContentPane().add(uni6, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 400, 579, 33));
        getContentPane().add(uni7, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 439, 579, 32));

        jButton1.setText("Add Student results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 518, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        sch.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(sch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(833, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(sch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(547, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into unitstwooneconfirmed(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
            
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
        }
        else if(jCheckBox4.isSelected()){
              
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into unitstwotwoconfirmed(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
            
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
     }
     else  if(jCheckBox5.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into unitsthreeoneconfirmed(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
            
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
          }
        else if(jCheckBox6.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into unitsthreetwoconfirmed(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
            
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
           }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void uni6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uni6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uni6ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
            try{
            String ses = jCheckBox3.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select regno,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where session=? and course=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, ses);
            pst.setString(2, cou);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome  Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
               
            }
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(cou);
            
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
         int row = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        uni1.setText(model.getValueAt(row, 1).toString());
        uni2.setText(model.getValueAt(row, 2).toString());
        uni3.setText(model.getValueAt(row, 3).toString());
        uni4.setText(model.getValueAt(row, 4).toString());
        uni5.setText(model.getValueAt(row, 5).toString());
        uni6.setText(model.getValueAt(row, 6).toString());
        uni7.setText(model.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
                  try{
            String ses = jCheckBox4.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select regno,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where session=? and course=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, ses);
            pst.setString(2, cou);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome  Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
               
            }
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
                        try{
            String ses = jCheckBox5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select regno,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where session=? and course=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, ses);
            pst.setString(2, cou);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome  Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
               
            }
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
       try{
            String ses = jCheckBox6.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select regno,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where session=? and course=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, ses);
            pst.setString(2, cou);
            ResultSet rs = pst.executeQuery();
           
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome  Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
               
            }
            
         
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Addmasks().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvisorConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvisorConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvisorConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvisorConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvisorConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sch;
    private javax.swing.JTable table;
    private javax.swing.JTextField uni1;
    private javax.swing.JTextField uni2;
    private javax.swing.JTextField uni3;
    private javax.swing.JTextField uni4;
    private javax.swing.JTextField uni5;
    private javax.swing.JTextField uni6;
    private javax.swing.JTextField uni7;
    // End of variables declaration//GEN-END:variables
}
