/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian Okungu
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Course
     */
    public static String Coursedone;
    public static String Schoolbelong;
    public static String Departmentbelong;
    public Course() {
        initComponents();
             try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select course,school,department from course";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    //JOptionPane.showMessageDialog(null,"Student Reported and Registered for Units");
                    Coursedone=rs.getString("course");
                    Schoolbelong = rs.getString("school");
                    Departmentbelong=rs.getString("department");
                    System.out.println(Coursedone);
                    System.out.println(Schoolbelong);
                    System.out.println(Departmentbelong);

                }else{
                    System.out.println("Variables does not work");
                    
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cname = new javax.swing.JTextField();
        yr = new javax.swing.JTextField();
        uni1 = new javax.swing.JTextField();
        ses = new javax.swing.JTextField();
        sch = new javax.swing.JTextField();
        dpt = new javax.swing.JTextField();
        uni4 = new javax.swing.JTextField();
        uni3 = new javax.swing.JTextField();
        uni5 = new javax.swing.JTextField();
        uni6 = new javax.swing.JTextField();
        uni7 = new javax.swing.JTextField();
        uni2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Add Course and Units");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 19, -1, -1));

        jLabel2.setText("Coursename");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 88, -1, -1));

        jLabel3.setText("School");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 135, -1, -1));

        jLabel4.setText("Department");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 179, -1, -1));

        jLabel5.setText("Session");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 217, 57, -1));

        jLabel6.setText("Year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 258, -1, -1));

        jLabel7.setText("Unit1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 296, 57, -1));

        jLabel8.setText("Unit2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 327, 57, -1));

        jLabel9.setText("Unit3");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 359, 57, -1));

        jLabel10.setText("Unit4");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 398, 36, -1));

        jLabel11.setText("Unit6");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 497, 36, -1));

        jLabel12.setText("Unit5");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 443, 36, 22));

        jLabel13.setText("Unit7");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 548, 36, -1));

        Cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnameActionPerformed(evt);
            }
        });
        getContentPane().add(Cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 85, 209, -1));
        getContentPane().add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 258, 209, -1));
        getContentPane().add(uni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 293, 209, -1));
        getContentPane().add(ses, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 214, 209, -1));
        getContentPane().add(sch, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 132, 209, -1));
        getContentPane().add(dpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 176, 209, -1));
        getContentPane().add(uni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 392, 210, -1));
        getContentPane().add(uni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 354, 209, -1));
        getContentPane().add(uni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 444, 211, -1));
        getContentPane().add(uni6, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 494, 211, -1));
        getContentPane().add(uni7, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 542, 211, -1));
        getContentPane().add(uni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 324, 209, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 573, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            PreparedStatement ps =null;
            String Course = Cname.getText();
            String School = sch.getText();
            String Session = ses.getText();
            String Department = dpt.getText();
            String Year = yr.getText();
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into cou(course,school,department,session,year,unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?,?,?,?,?,?)");
            
            ps.setString(1, Course);
            ps.setString(2, School);
            ps.setString(3, Session);
            ps.setString(4, Department);
            ps.setString(5, Year);
            
            ps.setString(6, unit1);
            ps.setString(7, unit2);
            ps.setString(8, unit3);
            ps.setString(9, unit4);
            ps.setString(10, unit5);
            ps.setString(11, unit6);
            ps.setString(12, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cname;
    private javax.swing.JTextField dpt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sch;
    private javax.swing.JTextField ses;
    private javax.swing.JTextField uni1;
    private javax.swing.JTextField uni2;
    private javax.swing.JTextField uni3;
    private javax.swing.JTextField uni4;
    private javax.swing.JTextField uni5;
    private javax.swing.JTextField uni6;
    private javax.swing.JTextField uni7;
    private javax.swing.JTextField yr;
    // End of variables declaration//GEN-END:variables
}
