/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

/**
 *
 * @author Brian Okungu
 */
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
    }
    public Data(String mag1,String mag2,String mag3,String mag4,String mag5,String mag6,String mag7){
        initComponents();
        Units uni = new Units();
        
        uni1.setText(mag1);
        uni2.setText(mag2);
        uni3.setText(mag3);
        uni4.setText(mag4);
        uni5.setText(mag5);
        uni6.setText(mag6);
        uni7.setText(mag7);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uni1 = new javax.swing.JLabel();
        uni2 = new javax.swing.JLabel();
        uni3 = new javax.swing.JLabel();
        uni4 = new javax.swing.JLabel();
        uni5 = new javax.swing.JLabel();
        uni6 = new javax.swing.JLabel();
        uni7 = new javax.swing.JLabel();
        con1 = new javax.swing.JLabel();
        con2 = new javax.swing.JLabel();
        con3 = new javax.swing.JLabel();
        con4 = new javax.swing.JLabel();
        con5 = new javax.swing.JLabel();
        con6 = new javax.swing.JLabel();
        con7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 150));

        uni1.setText("jLabel1");

        uni2.setText("jLabel2");

        uni3.setText("jLabel3");

        uni4.setText("jLabel4");

        uni5.setText("jLabel5");

        uni6.setText("jLabel6");

        uni7.setText("jLabel7");

        con1.setText("confirmed");

        con2.setText("confirmed");

        con3.setText("confirmed");

        con4.setText("confirmed");

        con5.setText("confirmed");

        con6.setText("confirmed");

        con7.setText("confirmed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uni1)
                    .addComponent(uni7)
                    .addComponent(uni6)
                    .addComponent(uni5)
                    .addComponent(uni4)
                    .addComponent(uni3)
                    .addComponent(uni2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(con1)
                    .addComponent(con2)
                    .addComponent(con3)
                    .addComponent(con4)
                    .addComponent(con5)
                    .addComponent(con6)
                    .addComponent(con7))
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni1)
                    .addComponent(con1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni2)
                    .addComponent(con2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni3)
                    .addComponent(con3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni4)
                    .addComponent(con4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni5)
                    .addComponent(con5))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni6)
                    .addComponent(con6))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni7)
                    .addComponent(con7))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel con1;
    public javax.swing.JLabel con2;
    public javax.swing.JLabel con3;
    public javax.swing.JLabel con4;
    public javax.swing.JLabel con5;
    public javax.swing.JLabel con6;
    public javax.swing.JLabel con7;
    public javax.swing.JLabel uni1;
    public javax.swing.JLabel uni2;
    public javax.swing.JLabel uni3;
    public javax.swing.JLabel uni4;
    public javax.swing.JLabel uni5;
    public javax.swing.JLabel uni6;
    public javax.swing.JLabel uni7;
    // End of variables declaration//GEN-END:variables
}
