/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Brian Okungu
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
   public String StudentCourse;
   public String StudentSchool;
   public String StudentDepartment;
   public String RegNumber;
   public String Pswd;
   public String fee1;
   public String fee2;
   public String fee3;
   public String fee4;
   public int pay;
   public int Amountpay;
   public int Balance;
    public Homepage() {
        initComponents();

        Tpanel1.setVisible(false);
       
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        c7.setVisible(false);
        
        
        fee2=jCheckBox4.getText();
        fee3=jCheckBox5.getText();
        fee4=jCheckBox6.getText();
        
           
    

         
   
        
    }
    public Homepage(String username1, String password1){
        initComponents();
        
        Tpanel1.setVisible(false);
       
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        c7.setVisible(false);
        firstname.setText(username1);
        regno.setText(password1);
        
                 try{
                RegNumber=firstname.getText();
                Pswd = regno.getText();
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select course,school,department from brian where RegNO=? and Password=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, RegNumber);
                pst.setString(2, Pswd);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    StudentCourse=rs.getString("course");
                    StudentSchool = rs.getString("school");
                    StudentDepartment=rs.getString("department");
                    
                    
                    //JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                    

                }else{
                    JOptionPane.showMessageDialog(null,"Wrong password or username");
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
                 
                 
         try{
            String reg=firstname.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amountpaid from feespaid where regno=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, reg);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                Amountpay = rs.getInt("Amountpaid");
                System.out.println(Amountpay);
                
              
                
            }else{
                System.out.println("we dont have");
                
                
               
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            System.out.print(firstname);
            
        }
    }
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Tpanel1 = new javax.swing.JTabbedPane();
        panel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        unit1 = new javax.swing.JTextField();
        unit2 = new javax.swing.JTextField();
        unit3 = new javax.swing.JTextField();
        unit4 = new javax.swing.JTextField();
        unit5 = new javax.swing.JTextField();
        unit6 = new javax.swing.JTextField();
        unit7 = new javax.swing.JTextField();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        r1 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        r5 = new javax.swing.JTextField();
        r6 = new javax.swing.JTextField();
        r7 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        brayo = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        panel5 = new javax.swing.JPanel();
        me = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lecC = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        ep = new javax.swing.JTextArea();
        panel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        uni1 = new javax.swing.JTextField();
        uni2 = new javax.swing.JTextField();
        uni3 = new javax.swing.JTextField();
        uni4 = new javax.swing.JTextField();
        uni5 = new javax.swing.JTextField();
        uni6 = new javax.swing.JTextField();
        uni7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        firstname = new javax.swing.JLabel();
        regno = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/backg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student home page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 40, -1, -1));

        jButton1.setText("Report session");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 143, 38));

        jButton2.setText("Show Units Registered");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 143, 34));

        jButton3.setText("Examination");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 143, 35));

        jButton4.setText("Fees");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 143, 32));

        jButton5.setText("RaiseComplain");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 143, 31));

        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1305, 200, -1, 0));

        panel2.setBackground(new java.awt.Color(255, 153, 153));

        jButton7.setText("Show");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "unit1", "unit2", "unit3", "unit4", "unit5", "unit6", "unit7"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        unit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit1ActionPerformed(evt);
            }
        });

        c1.setText("Confirmed");

        c2.setText("Confirmed");

        c3.setText("Confirmed");

        c4.setText("Confirmed");

        c5.setText("Confirmed");

        c6.setText("Confirmed");

        c7.setText("Confirmed");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(unit7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                            .addComponent(unit6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(70, 70, 70)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c1)
                            .addComponent(c2)
                            .addComponent(c3)
                            .addComponent(c4)
                            .addComponent(c5)
                            .addComponent(c6)
                            .addComponent(c7))
                        .addContainerGap(243, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unit2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c7))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Tpanel1.addTab("Units Registered", panel2);

        panel3.setBackground(new java.awt.Color(51, 255, 255));

        jCheckBox9.setText("1.1Results");

        jCheckBox10.setText("1.2Results");

        jCheckBox11.setText("2.1Results");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("2.2Results");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setText("3.1Results");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setText("3.2Results");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setText("4.1Results");

        jCheckBox16.setText("4.2Results");

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "unit1", "unit2", "unit3", "unit4", "unit5", "unit6", "unit7"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        brayo.setColumns(20);
        brayo.setRows(5);
        jScrollPane5.setViewportView(brayo);

        jButton9.setText("Generate");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton13.setText("Print");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox13))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox16)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton9)
                                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addComponent(jButton13)
                                .addGap(81, 81, 81))))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox14))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox16)
                            .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5)))
                .addGap(50, 50, 50)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton13))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Tpanel1.addTab("Examination", panel3);

        panel5.setBackground(new java.awt.Color(0, 51, 51));

        me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meActionPerformed(evt);
            }
        });

        jButton12.setText("SEND MESSAGE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPLIES");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Leccode");

        ep.setColumns(20);
        ep.setRows(5);
        jScrollPane6.setViewportView(ep);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12)
                            .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lecC, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        Tpanel1.addTab("RaiseComplain", panel5);

        panel1.setBackground(new java.awt.Color(102, 204, 255));

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Session1.1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Session1.2");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setText("Session2.1");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setText("Session2.2");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox5);
        jCheckBox5.setText("Session3.1");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox6);
        jCheckBox6.setText("Session3.2");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox7);
        jCheckBox7.setText("Session4.1");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox8);
        jCheckBox8.setText("Session4.2");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "uni1", "uni2", "uni3", "uni4", "uni5", "uni6", "uni7"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton6.setText("Register units");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        p1.setText("Pending..");

        p2.setText("Pending..");

        p3.setText("Pending..");

        p4.setText("Pending..");

        p5.setText("Pending..");

        p6.setText("Pending..");

        p7.setText("Pending..");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox6)
                                        .addComponent(jCheckBox5)
                                        .addComponent(jCheckBox4)
                                        .addComponent(jCheckBox3)
                                        .addComponent(jCheckBox2)
                                        .addComponent(jCheckBox1))
                                    .addComponent(jCheckBox7))
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p2)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(uni1)
                                        .addComponent(uni2)
                                        .addComponent(uni3)
                                        .addComponent(uni4)
                                        .addComponent(uni5)
                                        .addComponent(uni6)
                                        .addComponent(uni7, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(p1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(p3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(p4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(p5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(p6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(p7, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox8)
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(uni1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uni2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(p2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uni3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uni4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uni5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uni6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uni7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7))
                .addGap(4, 4, 4)
                .addComponent(jButton6)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        Tpanel1.addTab("Reportsession", panel1);

        panel4.setBackground(new java.awt.Color(0, 153, 153));

        jButton8.setText("PayFees");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText(" Fees Statement");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Fees Structure");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane4.setViewportView(area);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton8)
                        .addGap(44, 44, 44)
                        .addComponent(jButton10)
                        .addGap(40, 40, 40)
                        .addComponent(jButton11))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        Tpanel1.addTab("Fees", panel4);

        getContentPane().add(Tpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 50, -1, -1));

        firstname.setText("firstname");
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, 120, 30));
        getContentPane().add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage/backg.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Tpanel1.setVisible(true);
       Tpanel1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Tpanel1.setVisible(true);
       Tpanel1.setSelectedIndex(3);
       
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tpanel1.setVisible(true);
        Tpanel1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Tpanel1.setVisible(true);
        Tpanel1.setSelectedIndex(4);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
            System.out.println(StudentCourse);
// TODO add your handling code here:
        /*
               try{
                RegNumber=firstname.getText();
                Pswd = regno.getText();
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select course,school,department from brian where RegNO=? and Password=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, RegNumber);
                pst.setString(2, Pswd);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    StudentCourse=rs.getString("course");
                    StudentSchool = rs.getString("school");
                    StudentDepartment=rs.getString("department");
                    
                    
                    //JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                    

                }else{
                    JOptionPane.showMessageDialog(null,"Wrong password or username");
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
        */
            try{
            String Ses = jCheckBox3.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from cou where course=? and session =? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, StudentCourse);
            pst.setString(2, Ses);
          
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

          
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            
        }
               
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            String regno = firstname.getText();
            String ses = jCheckBox3.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into unitsregistered(course,regno,session,unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, StudentCourse);
            ps.setString(2, regno);
            ps.setString(3, ses);
            ps.setString(4, unit1);
            ps.setString(5, unit2);
            ps.setString(6, unit3);
            ps.setString(7, unit4);
            ps.setString(8, unit5);
            ps.setString(9, unit6);
            ps.setString(10, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
        }
        else if (jCheckBox4.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into registeredunitstwotwo(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
        }
       else if (jCheckBox5.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into registeredunitsthreeone(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
       }
            else if (jCheckBox6.isSelected()){
            PreparedStatement ps =null;
            String unit1=uni1.getText();
            String unit2=uni2.getText();
            String unit3 = uni3.getText();
            String unit4 = uni4.getText();
            String unit5 = uni5.getText();
            String unit6 = uni6.getText();
            String unit7 = uni7.getText();
            
           try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            ps= con.prepareStatement("insert into registeredunitsthreetwo(unit1,unit2,unit3,unit4,unit5,unit6,unit7)values(?,?,?,?,?,?,?)");
            ps.setString(1, unit1);
            ps.setString(2, unit2);
            ps.setString(3, unit3);
            ps.setString(4, unit4);
            ps.setString(5, unit5);
            ps.setString(6, unit6);
            ps.setString(7, unit7);
            ps.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Succefully updated");
         
           
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        
        }
        }
        
          
        p1.setVisible(true);
        p2.setVisible(true);
        p3.setVisible(true);
        p4.setVisible(true);
        p5.setVisible(true);
        p6.setVisible(true);
        p7.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        uni1.setText(model.getValueAt(row, 1).toString());
        uni2.setText(model.getValueAt(row, 2).toString());
        uni3.setText(model.getValueAt(row, 3).toString());
        uni4.setText(model.getValueAt(row, 4).toString());
        uni5.setText(model.getValueAt(row, 5).toString());
        uni6.setText(model.getValueAt(row, 6).toString());
        uni7.setText(model.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
           try{
            String Ses = jCheckBox4.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from cou where course=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, StudentCourse);
            pst.setString(2, Ses);
          
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

          
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
                      try{
            String Ses = jCheckBox5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from cou where course=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, StudentCourse);
            pst.setString(2, Ses);
          
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

          
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
                      try{
            String Ses = jCheckBox6.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from cou where course=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, StudentCourse);
            pst.setString(2, Ses);
          
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

          
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        if(jCheckBox3.isSelected()){
         try{
            String reg = firstname.getText();
            String ses = jCheckBox3.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where regno=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, reg);
            pst.setString(2, ses);
            ResultSet rs = pst.executeQuery();
           
            table2.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
        }
        else if(jCheckBox4.isSelected()){
                     try{
            String reg = firstname.getText();
            String ses = jCheckBox4.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where regno=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, reg);
            pst.setString(2, ses);
            ResultSet rs = pst.executeQuery();
           
            table2.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
        }
        else if(jCheckBox5.isSelected()){
          try{
            String reg = firstname.getText();
            String ses = jCheckBox5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where regno=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, reg);
            pst.setString(2, ses);
            ResultSet rs = pst.executeQuery();
           
            table2.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
        }
       else if(jCheckBox5.isSelected()){
        try{
            String reg = firstname.getText();
            String ses = jCheckBox5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select course,unit1,unit2,unit3,unit4,unit5,unit6,unit7 from unitsregistered where regno=? and session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, reg);
            pst.setString(2, ses);
            ResultSet rs = pst.executeQuery();
           
            table2.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome "+ RegNumber +" Your username and password matched");
                System.out.println("we have");
            }else{
                System.out.println("we dont have");
                System.out.println(StudentCourse);
            }
            
            
            
            
           
            
        }catch(Exception e){
            System.out.println("not connected");
            
        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void unit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unit1ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        int row = table2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table2.getModel();
        unit1.setText(model.getValueAt(row, 1).toString());
        unit2.setText(model.getValueAt(row, 2).toString());
        unit3.setText(model.getValueAt(row, 3).toString());
        unit4.setText(model.getValueAt(row, 4).toString());
        unit5.setText(model.getValueAt(row, 5).toString());
        unit6.setText(model.getValueAt(row, 6).toString());
        unit7.setText(model.getValueAt(row, 7).toString());
        
        
        c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
        c4.setVisible(true);
        c5.setVisible(true);
        c6.setVisible(true);
        c7.setVisible(true);
    }//GEN-LAST:event_table2MouseClicked

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
           try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from examinationtwoone";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table3.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "You Dont have Results for this Session Kindly Console with the COD");
            
        }
        
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
                       try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from examinationtwotwo";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table3.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "You Dont have Results for this Session Kindly Console with the COD");
            
        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
                       try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from examinationthreeone";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table3.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "You Dont have Results for this Session Kindly Console with the COD");
            
        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
            try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select * from examinationthreetwo";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
           
            table3.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
            
            
           
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "You Dont have Results for this Session Kindly Console with the COD");
            
        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        // TODO add your handling code here:
          int row = table3.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table3.getModel();
        r1.setText(model.getValueAt(row, 1).toString());
        r2.setText(model.getValueAt(row, 2).toString());
        r3.setText(model.getValueAt(row, 3).toString());
        r4.setText(model.getValueAt(row, 4).toString());
        r5.setText(model.getValueAt(row, 5).toString());
        r6.setText(model.getValueAt(row, 6).toString());
        r7.setText(model.getValueAt(row, 7).toString());
        
    }//GEN-LAST:event_table3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox3.isSelected()){
            try{
            fee1=jCheckBox3.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee1);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STATEMENT              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee1+ "\n");
                area.setText(area.getText()+"Amount paid = " + Amountpay+ "\n");
                area.setText(area.getText()+"Fees Balance = " + Balance+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        
        else if(jCheckBox4.isSelected()){
           try{
             fee2=jCheckBox4.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee2);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STATEMENT              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee2+ "\n");
                area.setText(area.getText()+"Amount paid = " + Amountpay+ "\n");
                area.setText(area.getText()+"Fee Balance = " + Balance+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        else if(jCheckBox5.isSelected()){
                   try{
             fee3=jCheckBox5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee3);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STATEMENT              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee3+ "\n");
                area.setText(area.getText()+"Amount paid = " + Amountpay+ "\n");
                area.setText(area.getText()+"Fee Balance = " + Balance+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        else if(jCheckBox6.isSelected()){
           try{
             fee4=jCheckBox6.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee4);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STATEMENT              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee4+ "\n");
                area.setText(area.getText()+"Amount  paid = " +Amountpay+ "\n");
                area.setText(area.getText()+"Fee Balance = " +Balance+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            try{
             fee1=jCheckBox3.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee1);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STRUCTURE              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee1+ "\n");
                area.setText(area.getText()+"Amount to be paid = " + pay+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        
        else if(jCheckBox4.isSelected()){
           try{
             fee2=jCheckBox4.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee2);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STRUCTURE              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee2+ "\n");
                area.setText(area.getText()+"Amount to be paid = " + pay+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        else if(jCheckBox5.isSelected()){
                   try{
             fee3=jCheckBox5.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where Session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee3);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STRUCTURE              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee3+ "\n");
                area.setText(area.getText()+"Amount to be paid = " + pay+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        else if(jCheckBox6.isSelected()){
           try{
             fee4=jCheckBox6.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            String sql = "Select Amount from payment where session=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, fee4);
            ResultSet rs = pst.executeQuery();
           

          
            if(rs.next()){
               
                pay = rs.getInt("Amount");
                Balance= (pay - Amountpay);
                area.setText("\n******************************************\n");
                area.setText(area.getText()+"*          FEES STRUCTURE              *\n");
                area.setText(area.getText()+"****************************************\n");
                
                
                area.setText(area.getText()+"Session = " + fee4+ "\n");
                area.setText(area.getText()+"Amount to be paid = " + pay+ "\n");
                
            }else{
                System.out.println("we dont have");
               
            }
            
  
        }catch(Exception e){
            System.out.println("not connected");
            System.out.println(pay);
            
        }
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       Tpanel1.setSelectedIndex(2);
        String Lec = firstname.getText();
        String Message;
        String reg;
        try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select lecnumber,reply from replies where regno=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, Lec);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                   Message=rs.getString("reply");
                   reg = rs.getString("lecnumber");
                
                
                ep.setText(ep.getText()+"Message:  " + Message+ "\n");
                ep.setText(ep.getText()+"Sender Number:  " + reg+ "\n");
                
                  

                }else{
                    JOptionPane.showMessageDialog(null,"Wrong password or username");
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
       /* LecHomepage lechmpg = new LecHomepage();
        lechmpg.label1.setText(jTextField1.getText());
        lechmpg.setVisible(true);
       LecHomepage mes = new LecHomepage();
       */
        String lec = lecC.getText();
        String message = me.getText();
        String stu = firstname.getText();
        String rep="";
        try{
            PreparedStatement pst=null;
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
            pst= con.prepareStatement("insert into studentlec(lecnumber,regno,complain,Replies)values(?,?,?,?)");
            pst.setString(1, lec);
            pst.setString(2, stu);
            pst.setString(3, message);
            pst.setString(4, rep);
            pst.executeUpdate();
                
            
            JOptionPane.showMessageDialog(null, "Message Sent Succefully");
         
            setVisible(false);
           
           
            //con.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter data in correct manner");
            System.out.print(e);
            
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String result1= r1.getText();
        String result2= r2.getText();
        String result3= r3.getText();
        String result4= r4.getText();
        String result5= r5.getText();
        String result6= r6.getText();
        String result7= r7.getText();
        
        
        brayo.setText("\n******************************************\n");
        brayo.setText(brayo.getText()+"*         RESULTS              *\n");
        brayo.setText(brayo.getText()+"****************************************\n");
                
                
        brayo.setText(brayo.getText()+"Unit 1 = " + result1+ "\n");
        brayo.setText(brayo.getText()+"Unit 2 = " +result2+ "\n");
        brayo.setText(brayo.getText()+"Unit 3 = " +result3+ "\n");
        brayo.setText(brayo.getText()+"Unit 4 = " +result4+ "\n");
        brayo.setText(brayo.getText()+"Unit 5 = " +result5+ "\n");
        brayo.setText(brayo.getText()+"Unit 6 = " +result6+ "\n");
        brayo.setText(brayo.getText()+"Unit 7 = " +result7+ "\n");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       try {
           // TODO add your handling code here:
           brayo.print();
       } catch (PrinterException ex) {
           Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tpanel1;
    private javax.swing.JTextArea area;
    private javax.swing.JTextArea brayo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JTextArea ep;
    private javax.swing.JLabel firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField lecC;
    private javax.swing.JTextField me;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JTextField r6;
    private javax.swing.JTextField r7;
    private javax.swing.JLabel regno;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTextField uni1;
    private javax.swing.JTextField uni2;
    private javax.swing.JTextField uni3;
    private javax.swing.JTextField uni4;
    private javax.swing.JTextField uni5;
    private javax.swing.JTextField uni6;
    private javax.swing.JTextField uni7;
    private javax.swing.JTextField unit1;
    private javax.swing.JTextField unit2;
    private javax.swing.JTextField unit3;
    private javax.swing.JTextField unit4;
    private javax.swing.JTextField unit5;
    private javax.swing.JTextField unit6;
    private javax.swing.JTextField unit7;
    // End of variables declaration//GEN-END:variables
}
