/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian Okungu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public  String StudentCourse;
    public  String StudentSchool;
    public String StudentDepartment;
    public Login() {
        initComponents();

        
    }
       public Login(String c, String sch, String dep) {
        initComponents();

          try{
                String user=username.getText();
                String pass=password.getText();
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select course,school,department from brian where RegNO=? and Password=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, user);
                pst.setString(2, pass);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    this.StudentCourse=rs.getString("course");
                    this.StudentSchool = rs.getString("school");
                    this.StudentDepartment=rs.getString("department");
                    
                    
                    System.out.println(StudentCourse);

                }else{
                    JOptionPane.showMessageDialog(null,"Wrong password or username");
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bl_username = new javax.swing.JLabel();
        bl_password = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnset = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(bl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 90, 113, 24));
        getContentPane().add(bl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 182, 138, 24));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 250, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Reg number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 10));

        btnset.setText("Reset");
        btnset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsetActionPerformed(evt);
            }
        });
        jPanel1.add(btnset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 74, 32));

        btnlog.setBackground(new java.awt.Color(255, 255, 153));
        btnlog.setText("Login");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        jPanel1.add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 68, 32));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
       String username1=username.getText();
       String password1=password.getText();
        if(username.getText().trim().isEmpty() && password.getText().trim().isEmpty()){
            bl_username.setText("Username is empty");
            bl_password.setText("Password is empty");
        }
        else if(username.getText().trim().isEmpty()){
            bl_username.setText("Username is empty");
        }
        else if(password.getText().trim().isEmpty()){
            bl_username.setText("Password is empty");
        }
        else{
            try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","");
                String sql = "Select course,school,department from brian where RegNO=? and Password=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, username1);
                pst.setString(2, password1);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    StudentCourse=rs.getString("course");
                    StudentSchool = rs.getString("school");
                    StudentDepartment=rs.getString("department");
                    
                    
                    JOptionPane.showMessageDialog(null, "Welcome "+ username1 +" Your username and password matched");
                    Homepage home = new Homepage();
                    home.setVisible(true);
                    setVisible(false);
                    new Homepage().setVisible(true);
                    new Homepage(username1,password1).setVisible(true);
                    setVisible(false);

                }else{
                    JOptionPane.showMessageDialog(null,"Wrong password or username");
                }
            }catch(Exception e){
                System.out.println("not connected");

            }
        }
        
        
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsetActionPerformed
        // TODO add your handling code here:
        String username1 = username.getText();
        String password1 = password.getText();
        username.setText("");
        password.setText("");
        username.requestFocus();
    }//GEN-LAST:event_btnsetActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        bl_username.setText("");
    }//GEN-LAST:event_usernameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bl_password;
    private javax.swing.JLabel bl_username;
    public javax.swing.JButton btnlog;
    private javax.swing.JButton btnset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
